name = "PkgTplTutorial101"
uuid = "c41f46c2-c8ad-4116-8660-e1ae41e18b43"
authors = ["jfd"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
